version: '3.8'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
  
  otp_service:
    build: ./otp_service
    ports:
      - "8001:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
